[package]
name = "politicas"
version = "0.1.0"
authors = ["Rafael Amadigi Dal Santo <rafael.dalsanto@mercos.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
